version: '3.7'

services:
  postgres:
    container_name: Postgres
    image: postgres:15.0
    env_file: .env
    ports:
      - 8080:5432
    volumes:
      - .\\volumes\\postgres-data\\:/var/lib/postgresql/data
  
  api:
    container_name: Api
    build:
      context: ./../
      dockerfile: ./src/Arenda.WebAPI/Dockerfile
    env_file: .env
    ports:
      - 8081:80
